### ISSUE TITLE
CUDA_ERROR_NOT_INITIALIZED

### ISSUE THREAD

**Issue by hunglc007** [pocokhc/agent57#3]
I am having trouble allocating GPU device for a multiprocessing. I have only one GPU, so I run `atari_pong.py` with agent57 model, 4 Actors and I am getting the CUDA_ERROR_NOT_INITIALIZED error. 
Have you tested your code with machine have only one GPU ?

**Comment by pocokhc** [comment]
Yes.
My environment has only one GPU.

``` bash
(py37-gpu) >python -c "from tensorflow.python.client import device_lib;print(device_lib.list_local_devices());"
(snip)
[name: "/device:CPU:0"
device_type: "CPU"
memory_limit: 268435456
locality {
}
incarnation: 641479775709840487
, name: "/device:GPU:0"
device_type: "GPU"
memory_limit: 2204421324
locality {
  bus_id: 1
  links {
  }
}
incarnation: 869804345080689859
physical_device_desc: "device: 0, name: GeForce GTX 1060 3GB, pci bus id: 0000:01:00.0, compute capability: 6.1"
]

```

I've tried it now, and I've verified that Learner works in my environment until it learns 100 times.
(atari_pong.py, 4 actors)

It's one possibility, but maybe it's due to lack of GPU specifications.
Did it work with one actor?

Or check the version of CUDA.

``` bash
(py37-gpu) >nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2019 NVIDIA Corporation
Built on Sun_Jul_28_19:12:52_Pacific_Daylight_Time_2019
Cuda compilation tools, release 10.1, V10.1.243
```

---
はい。
私の環境もGPUは１つだけです。

今試してみましたが、私の環境でLearnerが100回学習するまで動作することは確認しました。
（atari_pong.pyをアクター４人で）

１つの可能性ですが、もしかしたらGPUのスペック不足が原因の可能性があります。
アクターが一人の場合は動作しましたか？

または CUDA のバージョンを確認してみてください。
